---
title: "PharmacyInPractice"
author: "David Fong"
date: "27 August 2020"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)

library(pipeR)
library(dplyr)
library(dMeasure)
# setwd("C:/Users/david.fong/AppData/Local/Programs/GPstat/")
# source("dist/script/R/run.R")
```

## R 

```{r}
a <- dMeasure::dMeasure$new()
a$open_emr_db()
```

## active patients

```{r}
kensington_clinicians <- a$UserConfig %>>%
  filter(
    grepl(
      "Kensington",
      purrr::map_chr(Location, function(x) paste(x, collapse = ", "))
      # map_chr will create a 'collapsed' version of all the
      # listed locations
    )
  )

active_patient <- a$list_contact_count(
  date_from = as.Date("2017-10-01"), date_to = as.Date("2019-09-30"),
  clinicians = kensington_clinicians$Fullname,
  min_contact = 3,
  contact_type = "Services",
  lazy = FALSE, store = FALSE
)

active_patient_ID <- active_patient %>>% dplyr::pull(InternalID)

invoices <- a$db$invoices %>>%
  filter(InternalID %in% active_patient_ID) %>>%
  select(InvoiceID, InternalID)

invoiceID <- invoices %>>%
  pull(InvoiceID)

active_patient_billings <- a$emr_db$conn() %>>%
  tbl("SERVICES") %>>%
  select("SERVICEID", "SERVICEDATE", "INVOICEID", "MBSITEM", "PAID", "DESCRIPTION") %>>%
  filter(INVOICEID %in% invoiceID,
         as.Date(ServiceDate) >= as.Date("2017-10-01")) %>>%
  collect() %>>%
  rename(InvoiceID = INVOICEID, ServiceDate = SERVICEDATE,
         MBSItem = MBSITEM, Paid = PAID, Description = DESCRIPTION ) %>>%
  mutate(Description = trimws(Description),
         ServiceDate = as.Date(ServiceDate)) %>>%
  left_join(invoices %>>% collect(),
            by = "InvoiceID")

#active_patient_billings <- a$db$services %>>%
#  filter(
#    InternalID %in% active_patient_ID,
#    ServiceDate >= as.Date("2017-10-01")
#  ) %>>% dplyr::collect()
```

```{r}
LauraDeanVisits <- a$db$visits %>% filter(DrName == "Laura Dean")
# InternalID, VisitType, VisitDate, UserID, DrName
```

